language: node_js
node_js:
  - '12'
before_script:
  - npm ci
script:
  - npx stylelint "**/*.scss"
  - npm run affected:lint -- --base=origin/master --parallel
  - npm run affected:test -- --base=origin/master --parallel
  - npm run affected:e2e -- --base=origin/master --headless --parallel
after_script:
  - ./post_build_results
