on:
  release:
    types:
      - published

name: Upload release asset

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1.1.0
        with:
          node-version: "12.x"
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Application
        run: npm run build:admin
      - name: Compress Artifacts
        run: |
          cd dist/apps/admin
          zip -r -j ../../../admin.zip .
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./admin.zip
          asset_name: admin.zip
          asset_content_type: application/zip
