name: Push to Master

on:
  push:
    branches:
      - master

env: # https://stackoverflow.com/questions/59867124/how-can-i-access-github-action-environment-variables-within-a-bash-script-run-by
  STATUS: failing
  SHA: ${{ github.sha }}
  BRANCH: ${{ github.ref }}
  YELLR_KEY: ${{ secrets.YELLR_KEY }}
  YELLR_URL: ${{ secrets.YELLR_URL }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Application
        run: npx nx run-many --target=build --all --parallel
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js v12
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        # https://github.com/actions/cache/issues/193
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Stylelint
        run: npm run stylelint:ci
      - name: Lint
        run: npx nx run-many --target=lint --all --parallel --maxParallel=5
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js v12
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        # https://github.com/actions/cache/issues/193
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npx nx run-many --target=test --all --parallel --maxParallel=5 --bail=1
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js v12
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cache Cypress
        id: cypress-cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-cache-v2-
      - name: Install Cypress
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: npm i cypress@latest --save-dev
      - name: Test
        run: npx nx run-many --target=e2e --all --headless --parallel
